### ISSUE TITLE
Push Enabled property missing functionality.

### ISSUE THREAD

**Issue by ajoycekyrio** [pip-services3-node/pip-services3-prometheus-node#2]
# Overview

The PrometheusCounter class does not have the same functionality as the dotnet version.

I have implemented the fixes as individual commits and added it to a PR located [here](https://github.com/pip-services3-node/pip-services3-prometheus-node/pull/3)

# Issue

There seems to be an issue with prometheus that does not occur with the dotnet version.

From the logs

> Connection to Prometheus server is not configured: NO_CONNECTION: HTTP connection is not set

The config file

```yml
# Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"

# Prometheus keys service
- descriptor: "pip-services:metrics-service:prometheus:default:1.0"

# Prometheus performance counters
- descriptor: "pip-services:counters:prometheus:default:1.0"
  push_enabled: {{PUSHGATEWAY_METRICS_PUSH_ENABLED}}{{^PUSHGATEWAY_METRICS_PUSH_ENABLED}}false{{/PUSHGATEWAY_METRICS_PUSH_ENABLED}}
  {{#if PUSHGATEWAY_METRICS_ENABLED}}
  connection:
    protocol: http
    host: {{PUSHGATEWAY_METRICS_SERVICE_HOST}}
    port: {{PUSHGATEWAY_METRICS_SERVICE_PORT}}
  {{/if}}
```
**Fix**

The connection throws an error if it's not there, so to fix it we will check if we want to push using the _pushEnabled property

The code for the connection fix is below, this code can be found in the `PrometheusCounters` class.

```ts
open(correlationId, callback) {
	...
        ...

	if (!this._pushEnabled) {
		if(callback)
			callback(null);
		return;
	}

        ...
        ...
}

configure(config) {
    super.configure(config);
    this._connectionResolver.configure(config);
    this._source = config.getAsStringWithDefault("source", this._source);
    this._instance = config.getAsStringWithDefault("instance", this._instance);
    this._pushEnabled = config.getAsBooleanWithDefault("push_enabled", true);
}

 save(counters) {
    if (this._client == null || !this._pushEnabled)
        return;
    let body = PrometheusCounterConverter_1.PrometheusCounterConverter.toString(counters, null, null);
    this._client.put(this._requestRoute, body, (err, req, res, data) => {
        if (err || res.statusCode >= 400)
            this._logger.error("prometheus-counters", err, "Failed to push metrics to prometheus");
    });
}
```
